### ISSUE TITLE
Chapter 2 should contain minimal code

### ISSUE THREAD

**Issue by friendlyanon** [PacktPublishing/CMake-Tips-and-Tricks#2]
https://github.com/PacktPublishing/CMake-Tips-and-Tricks/blob/fb5a8f56ed153f874aa66f88cfeb97efd02b1efd/chapter_2/CMakeLists.txt#L17-L23

CMake has a better way to declare a standard requirement, which is [compile features](https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html#requiring-language-standards). This also propagates in the properties, which ensures that consuming a project's install interface will correctly set the standard when using `find_package()`. Not having this hardcoded also allows a project with conditionally compiled code to test each standard it supports. Configuring with `cmake --preset=dev -D CMAKE_CXX_STANDARD=XX` allows to substitue `XX` and to trivially create a matrix build in the CI that tests each standard. This also makes a project packageable, since the standard flag contributes to the ABI of the build artifacts.

https://github.com/PacktPublishing/CMake-Tips-and-Tricks/blob/fb5a8f56ed153f874aa66f88cfeb97efd02b1efd/chapter_2/CMakeLists.txt#L30-L35

Besides hardcoding these details, the Windows default of hidden by default is arguably the most correct behavior when symbol visibility is considered. I think shared libraries are a very heavy topic on their own that they could be either left for later. Shared libraries in C++ is a tricky subject, due to the ABI issue.

https://github.com/PacktPublishing/CMake-Tips-and-Tricks/blob/fb5a8f56ed153f874aa66f88cfeb97efd02b1efd/chapter_2/CMakeLists.txt#L48-L59

These install rules could be trimmed down considerably. First off, since [CMake 3.14](https://cmake.org/cmake/help/latest/release/3.14.html#commands), you are not required to spell out the destinations, because CMake will do the right thing by default. The `PUBLIC_HEADER` and `PRIVATE_HEADER` install blocks are only relevant for the MacOS specific [`FRAMEWORK`](https://cmake.org/cmake/help/latest/prop_tgt/FRAMEWORK.html) targets, for which you have to list the headers in the corresponding [`PUBLIC_HEADER`](https://cmake.org/cmake/help/latest/prop_tgt/PUBLIC_HEADER.html) and [`PRIVATE_HEADER`](https://cmake.org/cmake/help/latest/prop_tgt/PRIVATE_HEADER.html) target properties.

It's also missing proper componentization, which is important to properly set up links for .so files on platforms that do use .so files. The component should also be prefixed with a project specific identifier, so the component name does not cause issues in consuming projects when consumed using vendoring. This is something Craig Scott has also mentioned in his CppCon talk.

https://github.com/PacktPublishing/CMake-Tips-and-Tricks/blob/fb5a8f56ed153f874aa66f88cfeb97efd02b1efd/chapter_2/CMakeLists.txt#L61-L78

A bit pedantic, but while I'm here: This could just be moved into the driver's lists file, since there is already a check for the boolean variable.

---

Most of these things I have covered in the past in an educational example repository that contains some explanations for the what and why for each point. You can find it here: https://github.com/friendlyanon/cxx-static-shared-example

**Comment by mustafakemalgilor** [comment]
> CMake has a better way to declare a standard requirement, which is compile features. This also propagates in the properties, which ensures that consuming a project's install interface will correctly set the standard when using find_package(). Not having this hardcoded also allows a project with conditionally compiled code to test each standard it supports. Configuring with cmake --preset=dev -D CMAKE_CXX_STANDARD=XX allows to substitue XX and to trivially create a matrix build in the CI that tests each standard. This also makes a project packageable, since the standard flag contributes to the ABI of the build artifacts.

Thanks for the suggestion. Will be using target_compile_features() instead. 

> Besides hardcoding these details, the Windows default of hidden by default is arguably the most correct behavior when symbol visibility is considered. I think shared libraries are a very heavy topic on their own that they could be either left for later. Shared libraries in C++ is a tricky subject, due to the ABI issue.

This chapter has no intention of introducing shared libraries to the user. The visibility topic is addressed in Chapter 3. The shared library in this chapter's example is only added to provide variety.

The rest of the issues will be addressed in the merge request which will be associated with this issue.

**Comment by bernedom** [comment]
> Besides hardcoding these details, the Windows default of hidden by default is arguably the most correct behavior when symbol visibility is considered. I think shared libraries are a very heavy topic on their own that they could be either left for later. Shared libraries in C++ is a tricky subject, due to the ABI issue.

Hi @friendlyanon symbol visibility of DLLs is covered in chapter 3. The code example is still missing at the moment, but I'm on it.
